Repository Destronia/AdBlock_Filter, pull requests merged in 2022-06, with the labels that each got.

#17 Update assignees.
  .github/ISSUE_TEMPLATE/vulnerability-.md
  README.md
Labels: documentation

#18 Update to Filter List
  Destronia AdBlock Filter.txt
Labels: enhancement, filter list

#19 Update
  README.md
  filters/filters.txt
Labels: documentation, enhancement, filter list

#20 Update README.md
  README.md
Labels: documentation

#24 License Change
  LICENSE
Labels: documentation

#29 Update README.md
  README.md
Labels: documentation

#30 Improve English in README.md
  README.md
Labels: documentation
