Repository Destronia/AdBlock_Filter, pull requests merged in 2022-11, with the labels that each got.

#56 Fix PR Template
  docs/pull_request_template.md
Labels: documentation, enhancement

#60 Update filters.txt
  filters/filters.txt
Labels: documentation, enhancement, good first issue

#64 Update stale-issues.yml
  .github/workflows/stale-issues.yml
Labels: enhancement

#66 Fix typo in PULL_REQUEST_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement, good first issue

#67 Changes to README.md
  README.md
Labels: documentation, enhancement, good first issue

#69 Create bump-version.yml
  .github/workflows/bump-version.yml
  VERSION
Labels: enhancement, in-progress
